APT::FTPArchive::Release::Origin "LCOS";
APT::FTPArchive::Release::Label "LCOS";
APT::FTPArchive::Release::Suite "excalibur";
APT::FTPArchive::Release::Codename "excalibur";
APT::FTPArchive::Release::Architectures "amd64";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "LCOS overlay";
